// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyDanCu.Data;

#nullable disable

namespace QuanLyDanCu.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230725015622_addDB")]
    partial class addDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyDanCu.Models.CanHo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DienTich")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CanHos");
                });

            modelBuilder.Entity("QuanLyDanCu.Models.CuDan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThuongTru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CuDans");
                });

            modelBuilder.Entity("QuanLyDanCu.Models.CuDanCanHo", b =>
                {
                    b.Property<int>("CuDanId")
                        .HasColumnType("int");

                    b.Property<int>("CanHoId")
                        .HasColumnType("int");

                    b.HasKey("CuDanId", "CanHoId");

                    b.HasIndex("CanHoId");

                    b.ToTable("CuDanCanHos");
                });

            modelBuilder.Entity("QuanLyDanCu.Models.CuDanCanHo", b =>
                {
                    b.HasOne("QuanLyDanCu.Models.CanHo", "CanHo")
                        .WithMany("CuDanCanHos")
                        .HasForeignKey("CanHoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDanCu.Models.CuDan", "CuDan")
                        .WithMany("CuDanCanHos")
                        .HasForeignKey("CuDanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanHo");

                    b.Navigation("CuDan");
                });

            modelBuilder.Entity("QuanLyDanCu.Models.CanHo", b =>
                {
                    b.Navigation("CuDanCanHos");
                });

            modelBuilder.Entity("QuanLyDanCu.Models.CuDan", b =>
                {
                    b.Navigation("CuDanCanHos");
                });
#pragma warning restore 612, 618
        }
    }
}
